- name: debug
  debug:
    msg: "jeste gerrite"

- name: deb
  debug:
    msg: "{{app}}"

- name: install gerrit
  include_tasks: "install_{{app.value.gerrit.install}}.yml"
  when: app.value.gerrit.install|default(False)

- name: install pip
  yum:
    name: python2-pip
    state: installed
  become: True

- name: install requests
  pip:
    name: requests
    state: present
  become: True

- include_tasks: project.yml
  loop: "{{app.value.gerrit.configs.projects}}"
  loop_control:
    loop_var: project

- meta: flush_handlers

- include_tasks: consul_discovery.yml
