- name: daemon reload
  systemd:
    daemon_reload: yes
    name: "{{app.value.gerrit.user.user}}-gerrit.service"
  become: True

- name: gerrit restart
  service:
    name: "{{app.value.gerrit.user.user}}-gerrit"
    state: restarted
  become: True

- name: gerrit replication reload
  uri:
    url: "{{app.value.gerrit.endpoints.http.scheme}}://{{app.value.gerrit.endpoints.http.address}}:{{app.value.gerrit.endpoints.http.port}}/a/plugins/replication/gerrit~reload"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{app.value.gerrit.configs.auth.username}}"
      password: "{{app.value.gerrit.configs.auth.password}}"
